function getAlias(path, src) {
    return {
        /*"input": path.resolve(src, "platform/pay/js/com/Input/index"),
        "slide": path.resolve(src, "platform/pay/js/com/Slide/index"),
        "tabChannel": path.resolve(src, "platform/pay/js/com/TabChannel/index"),
        "tab": path.resolve(src, "platform/pay/js/com/Tab/index"),
        "step": path.resolve(src, "platform/pay/js/com/Step/index"),
        "radio": path.resolve(src, "platform/pay/js/com/Radio/index"),
        "payUtils": path.resolve(src, "platform/pay/js/com/Utils/index"),
        "commonModel": path.resolve(src, "platform/pay/js/commonModels/index"),
        "api":path.resolve(src,'platform/pay/js/gmStore/api'),
        "gmStore":path.resolve(src,'platform/pay/js/gmStore/gmStore'),
        "config": path.resolve(src, "platform/pay/js/config/index"),
        "channel": path.resolve(src, "platform/pay/js/config/channel"),
        "icon": path.resolve(src, "platform/pay/js/config/icon"),
        "ajaxData": path.resolve(src, "platform/pay/js/config/ajaxData"),
        "selectGameServer": path.resolve(src, "platform/pay/js/com/_selectGameServer/index"),
        "selectGameType": path.resolve(src, "platform/pay/js/com/_selectGameType/index"),
        "selectArea": path.resolve(src, "platform/pay/js/com/_selectArea/index"),
        "selectMoney": path.resolve(src, "platform/pay/js/com/_selectMoney/index"),
        "selectChannel": path.resolve(src, "platform/pay/js/com/_selectChannel/index"),
        "selectBank": path.resolve(src, "platform/pay/js/com/_selectBank/index"),
        "selectTelephoneType": path.resolve(src, "platform/pay/js/com/_selectTelephoneType/index"),
        "showUserInfo": path.resolve(src, "platform/pay/js/com/_showUserInfo/index"),
        "showMoneyTable": path.resolve(src, "platform/pay/js/com/_showMoneyTable/index"),
        "doSubmit": path.resolve(src, "platform/pay/js/com/_doSubmit/index"),
        "inputCard": path.resolve(src, "platform/pay/js/com/_inputCard/index"),
        "virtualAccount": path.resolve(src, "platform/pay/js/com/_virtualAccount/index"),
        'virtualInvoice': path.resolve(src, 'platform/pay/js/com/_virtualInvoice/index'),
        'writeMoney': path.resolve(src, 'platform/pay/js/com/_writeMoney/index'),
        "addTable": path.resolve(src, 'platform/pay/js/com/_addTable/index'),
        "showFitGame": path.resolve(src, 'platform/pay/js/com/_showFitGame/index'),
        "virtual": path.resolve(src, "platform/pay/js/channel/virtual/index"),
        "mycard": path.resolve(src, "platform/pay/js/channel/mycard/index"),
        "nganluongCard": path.resolve(src, "platform/pay/js/channel/nganluongCard/index"),
        "paypal": path.resolve(src, "platform/pay/js/channel/paypal/index"),
        "telephone": path.resolve(src, "platform/pay/js/channel/telephone/index"),
        "webATM": path.resolve(src, "platform/pay/js/channel/webATM/index")*/
    }
}
module.exports = getAlias;