define(function() {
  return {
    ZH: {
      "logoutFail":   "登出失败",
      "-10000":   "参数错误",
      "-20002":   "暂无角色",
      "-10001":   "请输入正确的验证码",
      "-10002":   "游戏维护中，请稍后再试。",
      "-10004":   "服务器维护中，请稍后再试。",
      "-10005":   "您选择的角色不存在",
      "-10006":   "您输入的序号与所选游戏不符！",
      "-10007":   "领取次数过多",
      "-10008":   "兑换失败",
      "-10009":   "请使用角色登入游戏后，再尝试",
      "-10010":   "奖励兑换失败，请使用角色登入游戏后，再尝试",
      "-10011":   "礼包码无法使用",
      "-10012":   "礼包码已过期",
      "-10013":   "礼包码已使用或不存在",
      "notGame":   "请选择游戏",
      "notServer":   "请选择服务器",
      "notRole":   "请选择角色",
      "notCard":   "请输入兑换码",
      "notCode":   "请输入验证码",
      "changeSucc":   "兑换成功",
      "-1004":   "请先登入",
      "homepage": "首页",
      "recharge": "储值",
      "service": "客服",
      "login": "登入",
      "register": "注册",
      "account": "我的帐号",
      "logout": "帐号登出",
      "codeexchange": "礼包码兑换页",
      "chosegame": "请选择游戏",
      "choseserver": "请选择伺服器",
      "chosecharacter": "请选择角色",
      "exchange": "兑换",
      "exchangelog": "兑换记录",
      "noticetitle": "注意事项",
      "line1": "1. 序列号启动后道具将自动发放至游戏内背包中，序列号请在截至日期前进行启动",
      "line2": "2. 注意序号的详细使用规则，以免出现启动失败的情况",
      "line3": "3. 最终解释权归Ujoy运营团队所有",
      "input-gift-code": "请输入礼包码",
      "input-verify-code": "请输入验证码",
      "nodata": "暂无数据",
      "norecord": "你暂无兑奖记录",
      "currlang": "简体中文"
    },
    TW: {
      "logoutFail":   "登出失敗",
      "-10000":   "參數錯誤",
      "-20002":   "暫無角色",
      "-10001":   "請輸入正確的驗證碼",
      "-10002":   "遊戲維護中，請稍後再試。",
      "-10004":   "服務器維護中，請稍後再試。",
      "-10005":   "您選擇的角色不存在",
      "-10006":   "您輸入的序號與所選遊戲不符！",
      "-10007":   "領取次數過多",
      "-10008":   "兌換失敗",
      "-10009":   "請使用角色登入遊戲後，再嘗試",
      "-10010":   "獎勵兌換失敗，請使用角色登入遊戲後，再嘗試",
      "-10011":   "禮包碼無法使用",
      "-10012":   "禮包碼已過期",
      "-10013":   "禮包碼已使用或不存在",
      "notGame":   "請選擇遊戲",
      "notServer":   "請選擇服務器",
      "notRole":   "請選擇角色",
      "notCard":   "請輸入兌換碼",
      "notCode":   "請輸入驗證碼",
      "changeSucc":   "兌換成功",
      "-1004":   "請先登入",
      "homepage": "首頁",
      "recharge": "儲值",
      "service": "客服",
      "login": "登入",
      "register": "註冊",
      "account": "我的帳號",
      "logout": "帳號登出",
      "codeexchange": "禮包碼兌換頁",
      "chosegame": "請選擇遊戲",
      "choseserver": "請選擇伺服器",
      "chosecharacter": "請選擇角色",
      "exchange": "兌換",
      "exchangelog": "兌換記錄",
      "noticetitle": "註意事項:",
      "line1": "1. 序列號啟動後道具將自動發放至遊戲內背包中，序列號請在截至日期前進行啟動;",
      "line2": "2. 註意序號的詳細使用規則，以免出現啟動失敗的情況;",
      "line3": "3. 最終解釋權歸Ujoy運營團隊所有;",
      "input-gift-code": "請輸入禮包碼",
      "input-verify-code": "請輸入驗證碼",
      "nodata": "暫無數據",
      "norecord": "暫無兌獎記錄",
      "currlang": "繁體中文"
    },
    EN: {
      "logoutFail":   "Failed to log out",
      "-10000":   "Parameter error",
      "-20002":   "Character not found",
      "-10001":   "Please enter the correct verification code",
      "-10002":   "Server is down for maintenance. Please try again later",
      "-10004":   "Server is down for maintenance. Please try again later",
      "-10005":   "Character not fount",
      "-10006":   "number doesn’t match the selected game",
      "-10007":   "Claim attempts used up",
      "-10008":   "Failed to exchange",
      "-10009":   "Please login to the game first",
      "-10010":   "Failed to exchange. Please login to the game first",
      "-10011":   "Invalid gift code",
      "-10012":   "Gift code has expired",
      "-10013":   "Gift code has been used or can’t be found",
      "notGame":   "Please select a game",
      "notServer":   "Please select a server",
      "notRole":   "Please select a character",
      "notCard":   "Please enter the code",
      "notCode":   "Please enter the verification code",
      "changeSucc":   "Success",
      "-1004":   "Please log out first",
      "homepage": "HOMEPAGE",
      "recharge": "RECHARGE",
      "service": "SERVICE",
      "login": "LOGIN",
      "register": "REGISTER",
      "account": "ACCOUNT",
      "logout": "LOGOUT",
      "codeexchange": "Code Exchange",
      "chosegame": "Select a game",
      "choseserver": "Select a server",
      "chosecharacter": "Select a character",
      "exchange": "Exchange",
      "exchangelog": "Log",
      "noticetitle": "Note:",
      "line1": "1. Gifts will be sent to your bag in game. Please exchange gifts before the deadline",
      "line2": "2. Be sure to check the rules of using the code in order to receive gifts successfully",
      "line3": "3. Ujoy operation team reserves all rights for the final explanation of the event",
      "input-gift-code": "Enter the gift code",
      "input-verify-code": "Verification code",
      "nodata": "No Data",
      "norecord": "No Record",
      "currlang": "English"
    }
  }
});
